language: node_js
node_js: 
  - "stable"
  

cache:
  directories:
    - "node_modules"

addons:
  code_climate:
    repo_token: 2f9a14edb203c6cd763f640f4051fbd78fea5e29b938dd4064f9f80805e19ac2

before_script:
  - npm install codeclimate-test-reporter nyc -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info

after_success: npm run coverage
